- job:
    name: openstack-chef-delivery
    parent: base
    description: Run Chef Delivery tests with openstack-chef
    required-projects: openstack/openstack-chef
    pre-run: playbooks/pre.yaml
    run: playbooks/delivery.yaml
    timeout: 2700

- job:
    name: openstack-chef-integration-bionic
    parent: base
    nodeset: ubuntu-bionic
    description: Run integration tests with openstack-chef on Ubuntu Bionic
    required-projects: openstack/openstack-chef
    pre-run: playbooks/pre.yaml
    run: playbooks/integration.yaml
    post-run: playbooks/post.yaml
    timeout: 3600

- job:
    name: openstack-chef-integration-xenial
    parent: openstack-chef-integration-bionic
    nodeset: ubuntu-xenial
    description: Run integration tests with openstack-chef on Ubuntu Xenial

- project-template:
    name: openstack-chef-jobs
    check:
      jobs:
        - openstack-chef-delivery
        - openstack-chef-integration-bionic:
            voting: false
        - openstack-chef-integration-xenial:
            voting: false
    gate:
      jobs:
        - openstack-chef-delivery

- project:
    templates:
      - publish-openstack-docs-pti
      - openstack-chef-jobs
