- job:
    name: openstack-chef-repo-delivery
    parent: base
    description: Run Chef Delivery tests with openstack-chef-repo
    required-projects: openstack/openstack-chef-repo
    pre-run: playbooks/pre.yaml
    run: playbooks/delivery.yaml
    timeout: 2700

- job:
    name: openstack-chef-repo-integration
    parent: base
    description: Run integration tests with openstack-chef-repo
    required-projects: openstack/openstack-chef-repo
    pre-run: playbooks/pre.yaml
    run: playbooks/integration.yaml
    post-run: playbooks/post.yaml
    timeout: 3600

- project-template:
    name: openstack-chef-repo-jobs
    check:
      jobs:
        - openstack-chef-repo-delivery
        - openstack-chef-repo-integration
    gate:
      jobs:
        - openstack-chef-repo-delivery
        - openstack-chef-repo-integration

- project:
    templates:
      - build-openstack-sphinx-docs-python3
      - openstack-chef-repo-jobs
