- job:
    name: openstack-chef-delivery
    parent: base
    description: Run Chef Delivery tests with openstack-chef
    required-projects: openstack/openstack-chef
    pre-run: playbooks/pre-delivery.yaml
    run: playbooks/delivery.yaml
    timeout: 1800

- job:
    name: openstack-chef-integration-ubuntu
    parent: base
    nodeset: ubuntu-bionic
    description: Run integration tests with openstack-chef on Ubuntu Bionic
    required-projects: openstack/openstack-chef
    pre-run: playbooks/pre-integration.yaml
    run: playbooks/integration.yaml
    post-run: playbooks/post.yaml
    timeout: 5400

- job:
    name: openstack-chef-minimal-integration-ubuntu
    parent: base
    nodeset: ubuntu-bionic
    description: Run minimal integration tests with openstack-chef on Ubuntu Bionic
    required-projects: openstack/openstack-chef
    pre-run: playbooks/pre-integration.yaml
    run: playbooks/minimal.yaml
    post-run: playbooks/post.yaml
    timeout: 5400

- job:
    name: openstack-chef-integration-centos
    parent: base
    nodeset: centos-7
    description: Run integration tests with openstack-chef on CentOS 7
    required-projects: openstack/openstack-chef
    pre-run: playbooks/pre-integration.yaml
    run: playbooks/integration.yaml
    post-run: playbooks/post.yaml
    timeout: 5400

- job:
    name: openstack-chef-minimal-integration-centos
    parent: base
    nodeset: centos-7
    description: Run minimal integration tests with openstack-chef on CentOS 7
    required-projects: openstack/openstack-chef
    pre-run: playbooks/pre-integration.yaml
    run: playbooks/minimal.yaml
    post-run: playbooks/post.yaml
    timeout: 5400

- project-template:
    name: openstack-chef-repo-jobs
    check:
      jobs:
        - openstack-chef-delivery
        - openstack-chef-integration-ubuntu
        - openstack-chef-integration-centos
    gate:
      queue: openstack-chef
      jobs:
        - openstack-chef-delivery
        - openstack-chef-integration-ubuntu
        - openstack-chef-integration-centos

- project-template:
    name: openstack-chef-jobs
    check:
      jobs:
        - openstack-chef-delivery
        - openstack-chef-integration-ubuntu
        - openstack-chef-integration-centos
        - openstack-chef-minimal-integration-ubuntu
        - openstack-chef-minimal-integration-centos
    gate:
      queue: openstack-chef
      jobs:
        - openstack-chef-delivery
        - openstack-chef-integration-ubuntu
        - openstack-chef-integration-centos
        - openstack-chef-minimal-integration-ubuntu
        - openstack-chef-minimal-integration-centos

- project:
    templates:
      - deploy-guide-jobs
      - publish-openstack-docs-pti
      - openstack-chef-repo-jobs
