- hosts: all
  tasks:
    - name: run integration
      shell:
        cmd: chef exec rake integration
        chdir: '{{ ansible_user_dir }}/src/opendev.org/openstack/openstack-chef'
      environment:
        TEST_ENVIRONMENT: '{{ chef_test_env | default("integration") }}'
        WORKSPACE: '{{ ansible_user_dir }}'
