- hosts: all
  roles:
    - bindep
  vars:
    bindep_file: /home/zuul/src/opendev.org/openstack/openstack-chef/bindep.txt

- hosts: all
  vars:
    release: 3.2.30
    chefdk: chefdk_{{ release }}-1_amd64.deb
  tasks:
  - name: Fetch chefdk package
    get_url:
      dest: /tmp/{{ chefdk }}
      url: https://packages.chef.io/files/stable/chefdk/{{ release }}/ubuntu/18.04/{{ chefdk }}
  - name: Install chefdk package
    shell: dpkg -i /tmp/{{ chefdk }}
    become: yes
  - name: Install newer fog-openstack gem
    shell: chef gem install fog-openstack --version '~> 1.0.0' --no-user-install --no-ri --no-rdoc
    become: yes
