- hosts: all
  roles:
    - bindep
  vars:
    bindep_file: /home/zuul/src/opendev.org/openstack/openstack-chef/bindep.txt

- hosts: all
  vars:
    release: 2.5.3
    chefdk: chefdk_{{ release }}-1_amd64.deb
  tasks:
  - name: Fetch chefdk package
    get_url:
      dest: /tmp/{{ chefdk }}
      url: https://packages.chef.io/files/stable/chefdk/{{ release }}/ubuntu/16.04/{{ chefdk }}
  - name: Install chefdk package
    shell: dpkg -i /tmp/{{ chefdk }}
    become: yes
  - name: Downgrade pip to 18.0 as workaround for https://github.com/poise/poise-python/issues/133
    shell: pip install pip==18.0
    become: yes

